# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: i201866 workflow
on:
  push:
    branches: ["i201866"]
  pull_request:
    branches: ["i201866"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build docker images
        run: docker-compose up db --build -d
      - name: Lint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test

  docker-push:
    # if the merge is to the main branch, then push the docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ca4-web:latest

      - name: Push Docker iamge
        run: |
          docker tag ca4-web:latest ${{ secrets.DOCKER_USERNAME }}/ca4-web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ca4-web:latest
