# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: main branch workflow (on merge)
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    types:
      - closed
permissions:
  contents: read

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build docker images
        run: docker-compose up --build -d

      - name: Lint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test

      - name: Push Docker iamge
        run: |
          docker tag ca4_web_1 ${{ secrets.DOCKER_USERNAME }}/ca4-web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ca4-web:latest

          docker tag ca4_db_2 ${{ secrets.DOCKER_USERNAME }}/ca4-db:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ca4-db:latest
